const Calc = require('./calc');
const CustomCalc = require('./CustomCalc');
const morzeconverter = require('./morzeConverter');
const romainConverter = require('./romainConverter');

const simple = new Calc();
console.log(simple.sum(10, 10));
console.log(simple.divide(10, 10));
console.log(simple.multiply(10, 10));
console.log(simple.subtract(10, 10));
const morze = new CustomCalc(morzeconverter);
console.log(morze.sum(10, 10));
console.log(morze.divide(10, 10));
console.log(morze.multiply(10, 10));
console.log(morze.subtract(10, 10));
const romain = new CustomCalc(romainConverter);
console.log(romain.sum(10, 10));
console.log(romain.divide(10, 10));
console.log(romain.multiply(10, 10));
console.log(romain.subtract(10, 10));
